name: timestamp

on:
  workflow_dispatch

jobs:
  thing:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Get Timestamp
      run: echo "time=Thing" >> "$GITHUB_OUTPUT"
    - name: Create timestamp file
      id: time
      env:
        TIME: ${{ steps.time.outputs.time }}
        ALL: ${{ join(steps.time.outputs.*, '\n') }}
      run: |
        echo $ALL
        echo $TIME > timestamp
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: Update timestamp to ${{ steps.time.outputs.time }}
        branch: actions/update-timestamp
        title: Update timestamp
        labels: |
          github_actions
          timestamp
      
